/*

This file was generated by the "C - Kessels engine grammar.h" template.

*/


wchar_t GrammarCharset0[1+1] = {
  10,
  0};
wchar_t GrammarCharset1[1+1] = {
  13,
  0};
wchar_t GrammarCharset2[1+1] = {
  8232,
  0};
wchar_t GrammarCharset3[1+1] = {
  8233,
  0};
wchar_t GrammarCharset4[23+1] = {
  9,
  11,
  12,
  32,
  133,
  160,
  5760,
  6158,
  8192,
  8193,
  8194,
  8195,
  8196,
  8197,
  8198,
  8199,
  8200,
  8201,
  8202,
  8230,
  8239,
  8287,
  12288,
  0};
wchar_t GrammarCharset5[1+1] = {
  45,
  0};
wchar_t GrammarCharset6[1+1] = {
  40,
  0};
wchar_t GrammarCharset7[1+1] = {
  41,
  0};
wchar_t GrammarCharset8[1+1] = {
  43,
  0};
wchar_t GrammarCharset9[9+1] = {
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  0};
wchar_t GrammarCharset10[1+1] = {
  48,
  0};
wchar_t GrammarCharset11[1+1] = {
  112,
  0};
wchar_t GrammarCharset12[1+1] = {
  42,
  0};
wchar_t GrammarCharset13[1+1] = {
  47,
  0};
wchar_t GrammarCharset14[10+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  0};
wchar_t GrammarCharset15[1+1] = {
  114,
  0};
wchar_t GrammarCharset16[1+1] = {
  105,
  0};
wchar_t GrammarCharset17[1+1] = {
  110,
  0};
wchar_t GrammarCharset18[1+1] = {
  116,
  0};



struct DfaEdgeStruct GrammarDfaEdgeArray0[14+1] = {
  {1,GrammarCharset0},
  {2,GrammarCharset1},
  {4,GrammarCharset2},
  {5,GrammarCharset3},
  {6,GrammarCharset4},
  {7,GrammarCharset5},
  {8,GrammarCharset6},
  {9,GrammarCharset7},
  {10,GrammarCharset8},
  {11,GrammarCharset9},
  {13,GrammarCharset10},
  {14,GrammarCharset11},
  {19,GrammarCharset12},
  {21,GrammarCharset13},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray1[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray2[1+1] = {
  {3,GrammarCharset0},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray3[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray4[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray5[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray6[1+1] = {
  {6,GrammarCharset4},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray7[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray8[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray9[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray10[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray11[1+1] = {
  {12,GrammarCharset14},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray12[1+1] = {
  {12,GrammarCharset14},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray13[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray14[1+1] = {
  {15,GrammarCharset15},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray15[1+1] = {
  {16,GrammarCharset16},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray16[1+1] = {
  {17,GrammarCharset17},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray17[1+1] = {
  {18,GrammarCharset18},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray18[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray19[1+1] = {
  {20,GrammarCharset13},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray20[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray21[2+1] = {
  {22,GrammarCharset12},
  {23,GrammarCharset13},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray22[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray23[0+1] = {
  {-1,NULL}};



int GrammarRuleSymbolArray0[2+1] = {
  16,
  17,
  -1};
int GrammarRuleSymbolArray1[0+1] = {
  -1};
int GrammarRuleSymbolArray2[4+1] = {
  15,
  9,
  18,
  10,
  -1};
int GrammarRuleSymbolArray3[3+1] = {
  19,
  13,
  18,
  -1};
int GrammarRuleSymbolArray4[3+1] = {
  19,
  8,
  18,
  -1};
int GrammarRuleSymbolArray5[1+1] = {
  19,
  -1};
int GrammarRuleSymbolArray6[3+1] = {
  20,
  11,
  19,
  -1};
int GrammarRuleSymbolArray7[3+1] = {
  20,
  12,
  19,
  -1};
int GrammarRuleSymbolArray8[1+1] = {
  20,
  -1};
int GrammarRuleSymbolArray9[1+1] = {
  14,
  -1};
int GrammarRuleSymbolArray10[3+1] = {
  9,
  18,
  10,
  -1};


struct ActionStruct GrammarLalrActionArray0[4+1] = {
  {15,1,1},
  {16,3,2},
  {17,3,3},
  {0,2,1},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray1[1+1] = {
  {9,1,4},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray2[4+1] = {
  {15,1,1},
  {16,3,2},
  {17,3,5},
  {0,2,1},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray3[1+1] = {
  {0,4,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray4[5+1] = {
  {9,1,6},
  {14,1,7},
  {18,3,8},
  {19,3,9},
  {20,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray5[1+1] = {
  {0,2,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray6[5+1] = {
  {9,1,6},
  {14,1,7},
  {18,3,11},
  {19,3,9},
  {20,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray7[5+1] = {
  {8,2,9},
  {10,2,9},
  {11,2,9},
  {12,2,9},
  {13,2,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray8[1+1] = {
  {10,1,12},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray9[3+1] = {
  {8,1,13},
  {13,1,14},
  {10,2,5},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray10[5+1] = {
  {11,1,15},
  {12,1,16},
  {8,2,8},
  {10,2,8},
  {13,2,8},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray11[1+1] = {
  {10,1,17},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray12[2+1] = {
  {0,2,2},
  {15,2,2},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray13[5+1] = {
  {9,1,6},
  {14,1,7},
  {18,3,18},
  {19,3,9},
  {20,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray14[5+1] = {
  {9,1,6},
  {14,1,7},
  {18,3,19},
  {19,3,9},
  {20,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray15[4+1] = {
  {9,1,6},
  {14,1,7},
  {19,3,20},
  {20,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray16[4+1] = {
  {9,1,6},
  {14,1,7},
  {19,3,21},
  {20,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray17[5+1] = {
  {8,2,10},
  {10,2,10},
  {11,2,10},
  {12,2,10},
  {13,2,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray18[1+1] = {
  {10,2,4},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray19[1+1] = {
  {10,2,3},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray20[3+1] = {
  {8,2,6},
  {10,2,6},
  {13,2,6},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray21[3+1] = {
  {8,2,7},
  {10,2,7},
  {13,2,7},
  {-1,-1,-1}};



/*
struct SymbolStruct {
  short Kind;
  char *Name;
  };
*/
struct SymbolStruct GrammarSymbolArray[21] = {
  /*  0 */   {3,"EOF"},
  /*  1 */   {7,"Error"},
  /*  2 */   {2,"Comment"},
  /*  3 */   {2,"NewLine"},
  /*  4 */   {2,"Whitespace"},
  /*  5 */   {5,"*/"},
  /*  6 */   {4,"/*"},
  /*  7 */   {6,"//"},
  /*  8 */   {1,"-"},
  /*  9 */   {1,"("},
  /* 10 */   {1,")"},
  /* 11 */   {1,"*"},
  /* 12 */   {1,"/"},
  /* 13 */   {1,"+"},
  /* 14 */   {1,"DecLiteral"},
  /* 15 */   {1,"print"},
  /* 16 */   {0,"Calculate"},
  /* 17 */   {0,"Calculations"},
  /* 18 */   {0,"Expression"},
  /* 19 */   {0,"MultiplyDivide"},
  /* 20 */   {0,"Value"} 
  };



/*
struct DfaEdgeStruct {
  int TargetState;
  char *CharacterSet;
  };
struct DfaStateStruct {
  int AcceptSymbol;
  int EdgeCount;
  struct DfaEdgeStruct *Edges;
  };
*/
struct DfaStateStruct GrammarDfaStateArray[24+1] = {
  /* 0 */    {-1,14,GrammarDfaEdgeArray0},
  /* 1 */    {3,0,GrammarDfaEdgeArray1},
  /* 2 */    {3,1,GrammarDfaEdgeArray2},
  /* 3 */    {3,0,GrammarDfaEdgeArray3},
  /* 4 */    {3,0,GrammarDfaEdgeArray4},
  /* 5 */    {3,0,GrammarDfaEdgeArray5},
  /* 6 */    {4,1,GrammarDfaEdgeArray6},
  /* 7 */    {8,0,GrammarDfaEdgeArray7},
  /* 8 */    {9,0,GrammarDfaEdgeArray8},
  /* 9 */    {10,0,GrammarDfaEdgeArray9},
  /* 10 */    {13,0,GrammarDfaEdgeArray10},
  /* 11 */    {14,1,GrammarDfaEdgeArray11},
  /* 12 */    {14,1,GrammarDfaEdgeArray12},
  /* 13 */    {14,0,GrammarDfaEdgeArray13},
  /* 14 */    {-1,1,GrammarDfaEdgeArray14},
  /* 15 */    {-1,1,GrammarDfaEdgeArray15},
  /* 16 */    {-1,1,GrammarDfaEdgeArray16},
  /* 17 */    {-1,1,GrammarDfaEdgeArray17},
  /* 18 */    {15,0,GrammarDfaEdgeArray18},
  /* 19 */    {11,1,GrammarDfaEdgeArray19},
  /* 20 */    {5,0,GrammarDfaEdgeArray20},
  /* 21 */    {12,2,GrammarDfaEdgeArray21},
  /* 22 */    {6,0,GrammarDfaEdgeArray22},
  /* 23 */    {7,0,GrammarDfaEdgeArray23},
  {-1,-1,NULL}};



/*
struct RuleStruct {
  int Head;
  int SymbolsCount;
  int *Symbols;
  char *Description;
  };
*/
struct RuleStruct GrammarRuleArray[11] = {
  /*  0 */   {17,2,GrammarRuleSymbolArray0,"<Calculations> ::= <Calculate> <Calculations>"},
  /*  1 */   {17,0,GrammarRuleSymbolArray1,"<Calculations> ::= "},
  /*  2 */   {16,4,GrammarRuleSymbolArray2,"<Calculate> ::= print '(' <Expression> ')'"},
  /*  3 */   {18,3,GrammarRuleSymbolArray3,"<Expression> ::= <MultiplyDivide> '+' <Expression>"},
  /*  4 */   {18,3,GrammarRuleSymbolArray4,"<Expression> ::= <MultiplyDivide> '-' <Expression>"},
  /*  5 */   {18,1,GrammarRuleSymbolArray5,"<Expression> ::= <MultiplyDivide>"},
  /*  6 */   {19,3,GrammarRuleSymbolArray6,"<MultiplyDivide> ::= <Value> '*' <MultiplyDivide>"},
  /*  7 */   {19,3,GrammarRuleSymbolArray7,"<MultiplyDivide> ::= <Value> '/' <MultiplyDivide>"},
  /*  8 */   {19,1,GrammarRuleSymbolArray8,"<MultiplyDivide> ::= <Value>"},
  /*  9 */   {20,1,GrammarRuleSymbolArray9,"<Value> ::= DecLiteral"},
  /* 10 */   {20,3,GrammarRuleSymbolArray10,"<Value> ::= '(' <Expression> ')'"} 
  };



/*
struct ActionStruct {
  int Entry;
  short Action;
  int Target;
  };
struct LalrStateStruct {
  int ActionCount;
  struct ActionStruct *Actions;
  };
*/
struct LalrStateStruct GrammarLalrStateArray[22+1] = {
  /* 0 */   {4,GrammarLalrActionArray0},
  /* 1 */   {1,GrammarLalrActionArray1},
  /* 2 */   {4,GrammarLalrActionArray2},
  /* 3 */   {1,GrammarLalrActionArray3},
  /* 4 */   {5,GrammarLalrActionArray4},
  /* 5 */   {1,GrammarLalrActionArray5},
  /* 6 */   {5,GrammarLalrActionArray6},
  /* 7 */   {5,GrammarLalrActionArray7},
  /* 8 */   {1,GrammarLalrActionArray8},
  /* 9 */   {3,GrammarLalrActionArray9},
  /* 10 */   {5,GrammarLalrActionArray10},
  /* 11 */   {1,GrammarLalrActionArray11},
  /* 12 */   {2,GrammarLalrActionArray12},
  /* 13 */   {5,GrammarLalrActionArray13},
  /* 14 */   {5,GrammarLalrActionArray14},
  /* 15 */   {4,GrammarLalrActionArray15},
  /* 16 */   {4,GrammarLalrActionArray16},
  /* 17 */   {5,GrammarLalrActionArray17},
  /* 18 */   {1,GrammarLalrActionArray18},
  /* 19 */   {1,GrammarLalrActionArray19},
  /* 20 */   {3,GrammarLalrActionArray20},
  /* 21 */   {3,GrammarLalrActionArray21},
  {-1,NULL}};



/*
struct GrammarStruct {
  char CaseSensitive;
  int InitialSymbol;
  int InitialDfaState;
  int InitialLalrState;
  int SymbolCount;
  struct SymbolStruct *SymbolArray;
  int RuleCount;
  struct RuleStruct *RuleArray;
  int DfaStateCount;
  struct DfaStateStruct *DfaArray;
  int LalrStateCount;
  struct LalrStateStruct *LalrArray;
  };
*/
struct GrammarStruct Grammar = {
  /* CaseSensitive */      ,
  /* InitialSymbol */      ,
  /* InitialDfaState */    0,
  /* InitialLalrState */   0,
  /* SymbolCount */        21,
  /* SymbolArray */        GrammarSymbolArray,
  /* RuleCount */          11,
  /* RuleArray */          GrammarRuleArray,
  /* DfaStateCount */      24,
  /* DfaArray */           GrammarDfaStateArray,
  /* LalrStateCount */     22,
  /* LalrArray */          GrammarLalrStateArray
  };
